### ISSUE TITLE
jVectorMap doesnt load

### ISSUE THREAD

**Issue by cruisemaniac** [tarunvelli/rails-tabler-starter#2]
Upon creating a new space, the map under the location div does not load.

The error in the browser console is:

```
Uncaught ReferenceError: jsVectorMap is not defined
    at HTMLDocument.<anonymous> (<anonymous>:4:16)
    at dispatch (turbo.es2017-esm.js:315:34)
    at Session.notifyApplicationAfterPageLoad (turbo.es2017-esm.js:2729:16)
    at Session.visitCompleted (turbo.es2017-esm.js:2647:14)
    at Navigator.visitCompleted (turbo.es2017-esm.js:2126:23)
    at Visit.complete (turbo.es2017-esm.js:1454:27)
    at turbo.es2017-esm.js:1519:26
    at async Visit.render (turbo.es2017-esm.js:1682:9)
```

**Comment by tarunvelli** [comment]
Resolved in https://github.com/tarunvelli/rails-tabler-starter/pull/1, thanks again for the contribution!
